#!/usr/bin/env bash

set -e

sudo apt-get update && sudo apt-get upgrade -y

sudo apt install -y \
  curl \
  git \
  wget \
  unzip \
  zip \
  ca-certificates \
  openssh-server

sudo passwd root

sudo tee /etc/ssh/sshd_config.d/root.conf > /dev/null <<'EOF'
PermitRootLogin yes
PasswordAuthentication yes
PubkeyAuthentication no
EOF

sudo systemctl restart ssh

echo "server ALL=(root) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/server-nopasswd
